display_errors=Off
log_errors=On
error_reporting=E_ALL & ~E_DEPRECATED & ~E_USER_DEPRECATED
memory_limit=512M
max_execution_time=300
max_input_time=300
max_input_vars=10000
post_max_size=128M
upload_max_filesize=128M
date.timezone=Africa/Cairo
session.save_path=/tmp
